id: spark
namespace: dev

variables:
  gcs_url_base: "gs://{{kv('GCP_BUCKET_URL')}}/{{kv('GCP_DATASET')}}/partitioned/"

tasks:
  - id: each
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ trigger.blobs | jq('.[].uri') }}"
    tasks:
      - id: return
        type: io.kestra.plugin.core.log.Log
        message: "{{taskrun.value}}"
      
  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles

triggers:
  - id: watch
    type: io.kestra.plugin.gcp.gcs.Trigger
    interval: PT10M
    from: "{{vars.gcs_url_base}}"
    action: NONE


pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDENTIALS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_URL')}}"